### ISSUE TITLE
Create flowMatrix from pathfinder response

### ISSUE THREAD

**Issue by shrn-werk** [aboutcircles/circles-sdk#11]
As a Circles SDK developer I want to re-use the existing [pathfinder](https://github.com/CirclesUBI/pathfinder2) service to calculate payment paths. Since the transfer operation changed significantly between v1 and v2 I need an adapter that allows me to convert the pathfinder's json response to valid call data for the v2 contract's `operateFlowMatrix` function.

Acceptance:

- [X] The implementation from [https://github.com/aboutcircles/circles-sdk/pull/5/files](https://github.com/aboutcircles/circles-sdk/pull/5/files) is included in the sdk for v2 transfers
- [X] Implementation is tested against a pathfinder with v2 data and working

**Comment by jaensen** [comment]
[https://github.com/aboutcircles/circles-sdk/blob/dev/packages/sdk/src/v2/pathfinderV2.ts](https://github.com/aboutcircles/circles-sdk/blob/dev/packages/sdk/src/v2/pathfinderV2.ts)
